# Generated by Django 5.1.4 on 2025-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('truck_driver', 'Truck Driver'), ('dispatcher', 'Dispatcher')], max_length=20, null=True),
        ),
    ]
