# Generated by Django 5.1.4 on 2025-01-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=13)),
                ('olib_ketish', models.CharField(max_length=70)),
                ('tashlab_ketish', models.CharField(max_length=70)),
                ('yuk_turi', models.CharField(max_length=30)),
                ('yuk_vazni', models.IntegerField()),
                ('yuk_hajmi', models.IntegerField()),
                ('transport_turi', models.CharField(choices=[('truck', 'TRUCK'), ('trailer', 'TRAILER')], max_length=30)),
                ('yuk_moshina_soni', models.IntegerField(default=1)),
                ('uzunlik', models.IntegerField(max_length=6)),
                ('kenglik', models.IntegerField(max_length=6)),
                ('balandlik', models.IntegerField(max_length=6)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
