# Generated by Django 5.1.4 on 2025-01-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_products_balandlik_alter_products_kenglik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_type',
            field=models.CharField(choices=[('uzs', 'UZS'), ('usd', 'USD'), ('eur', 'EUR')], default='uzs', max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='balandlik',
            field=models.IntegerField(verbose_name='Balandlik (m)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='kenglik',
            field=models.IntegerField(verbose_name='Kenglik (m)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='uzunlik',
            field=models.IntegerField(verbose_name='Uzunlik (m)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='yuk_hajmi',
            field=models.IntegerField(verbose_name='Yuk hajmi (m3)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='yuk_vazni',
            field=models.IntegerField(verbose_name='Yuk vazni (t)'),
        ),
    ]
